### ISSUE TITLE
TODO: if specificShortCode exists, retry with another specificShortCode or generate a randomShortCode .

### ISSUE THREAD

**Issue by Chirag482** [scaleracademy/sclr.ac-backend#10]

**Comment by Chirag482** [comment]
reference : https://github.com/scaleracademy/sclr.ac-backend/blob/main/src/controllers/shortcode.controller.ts#L20

**Comment by championswimmer** [comment]
If specific shortcode doesn't exist we must give error to frontend, not try another, because user explicitly asked for this shortcode, and we cannot provide them with alternate
