### ISSUE TITLE
INFRA: create a heroku config file so this can be deployed on heroku 

### ISSUE THREAD

**Issue by championswimmer** [scaleracademy/sclr.ac-backend#11]

**Comment by harikanani** [comment]
@championswimmer should we use docker to run our postgreSQL Database?

**Comment by championswimmer** [comment]
For Heroku we can use the heroku postgres plugin

**Comment by Kartikdot** [comment]
Taking this up. Let me know if this is taken by someone else/ already completed.

**Comment by harikanani** [comment]
No @Kartik2016 , You can start working on this issue

**Comment by Kartikdot** [comment]
@championswimmer Kindly review the PR.
Note: for using with heroku postgres plugin, we will have to set "PGSSLMODE" to "no-verify" in Heroku config or add extra options in typeorm production config. I could not test with custom SSL certificate since it required paid dynamos on heroku.
