### ISSUE TITLE
TODO: retry if shortcode exists, and generate a new one and try again

### ISSUE THREAD

**Issue by championswimmer** [scaleracademy/sclr.ac-backend#2]
reference: https://github.com/scaleracademy/sclr.ac-backend/blob/a7c80a69194c86eba88725a4485340412a2a5766/src/controllers/shortcode.controller.ts#L10

**Comment by AVS18** [comment]
I can take up this issue

**Comment by AVS18** [comment]
Hi, I can take this issue up. @championswimmer

**Comment by championswimmer** [comment]
@AVS18 sure go ahead :)

**Comment by AVS18** [comment]
info: please complete authentication in your browser...
remote: Permission to scaleracademy/sclr.ac-backend.git denied to AVS18.
fatal: unable to access 'https://github.com/scaleracademy/sclr.ac-backend.git/': The requested URL returned error: 403
