### ISSUE TITLE
TODO: in custom short code creation validate less than 8 chars

### ISSUE THREAD

**Issue by championswimmer** [scaleracademy/sclr.ac-backend#3]
In the route, we must validate the requested code is <= 8 char, and if not, throw send an error response

https://github.com/scaleracademy/sclr.ac-backend/blob/a7c80a69194c86eba88725a4485340412a2a5766/src/routes/api.ts#L7

**Comment by kudoabhijeet** [comment]
@championswimmer we would have to validate length of requested code and if it already exists on `PUT /api/urls/{code}`  I think, i.e:
```typescript
route.put('/urls/:code', async (req, res) => {
    const shortCode = req.params.code // <-- here
    const longUrl = req.body.url
  
    // if note create a specific short code and return a success(201) response
    const savedShortCode = await createSpecificShortCode(shortCode, longUrl)

    return res.status(201).json({
        status: "success",
        data: savedShortCode
    })
})
```
correct me if this is not the case.

**Comment by harikanani** [comment]
@championswimmer assign this task to me I'll start working on it.

**Comment by harikanani** [comment]
@kudoabhijeet I guess it isn't resolved yet, We can't also use 8 length of characters but as in the issue, It's also requested.

**Comment by kudoabhijeet** [comment]
@harikanani this is a url shortner, so we have to keep a check if the requested shortcode is <=8 always, all other cases (>8) should throw an error. Probably, `400 (Bad Request)`.
